name: Danger

on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
    - name: Install Danger
      run: brew install danger/tap/danger-swift
    - name: Run Danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: danger-swift ci
