name: Danger Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  danger-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7"
      
      - name: Install Danger Swift
        run: |
          brew install danger/tap/danger-swift
      
      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: danger-swift ci
